DELETE http://localhost:3003/api/blogs/631e9f33a115bfb448893228
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzMWU2ZGVhYTdmYzBjYmNiYmIyYmJmYyIsImlhdCI6MTY2MzMwMjIzN30.bHvBCRJYHa7AomDPjW-uux-MMZe7NmbVp8yzjGzm6FM